### ISSUE TITLE
youtube-dl遭到DMCA takedown，更新脚本运行错误

### ISSUE THREAD

**Issue by laomocode** [coslyk/moonplayer#100]
Youtube-dl仓库被DMCA takedown，目前已无法访问。更新脚本无法更新插件，是否能在之后的版本将更新脚本删除关于更新Youtube-dl的内容？
目前更新脚本运行结果如下：
```
-------- Checking youtube-dl's updates -------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Cannot get the latest version of youtube-dl. Please try again later.

```
![image](https://user-images.githubusercontent.com/53001527/97065991-09701800-15e4-11eb-821b-8d91dd21e515.png)

目前访问youtube-dl仓库情况如下：
![github com_ytdl-org_youtube-dl](https://user-images.githubusercontent.com/53001527/97066010-2f95b800-15e4-11eb-92d4-f0bfae44137b.png)

**Comment by coslyk** [comment]
谢谢反馈，移除了自动下载youtube-dl的功能，有需要继续使用的可以自己下载youtube-dl并放到PATH里
