### ISSUE TITLE
系统是mac os 10.12.6 无法更新解析程序

### ISSUE THREAD

**Issue by chingrun** [coslyk/moonplayer#81]
**在提交前，请确保您已经检查了以下内容! / Before submitting an issue, please check the following points!**

* 您确实可以在浏览器或移动端中观看视频，但不能使用MoonPlayer播放或下载。/ You can watch the video in browser or in phone apps, but can't watch it in MoonPlayer.
* 您已更新视频解析程序至最新版本。（右键-更新解析程序，然后重启MoonPlayer）/ You have upgraded the video parser to the newest version. (In right-click menu, choose "Upgrade parsers", then relaunch MoonPlayer)
* 如果是因为您手动添加插件导致程序无法启动，请移除插件后重试。/ If the problem happens after you add a plugin manually, try removing it and relaunch.
* 若已经有人报告过相同的问题，请在原Issue下跟帖，而不是另外开一个Issue。/ If someone has submitted the same issue, please report in the old one instead of opening a new issue.
* 本问题确实关于MoonPlayer，而不是其他项目。/ The issue is related to MoonPlayer, not to other projects.

**请将错误输出粘贴在下面: / Please paste the error output here:**
* 若问题是有关于视频解析失败的，请在错误提示窗口中点击“详细信息”，并复制详细信息在这里！/ If your issue is related to the video parsing, please click "Details..." in the error dialog, and copy the detailed information here!
* 若问题关于程序本身，请贴出终端下的错误输出！/ If the issue is related to the program itself, please paste the error output in terminal!
=> Upgrading ykdl
Current version: not installed
Traceback (most recent call last):
File "/Applications/MoonPlayer.app/Contents/Resources/plugins/upgrade_extras.py", line 75, in <module>
latest_ver = get_latest_commit('zhangn1985/ykdl')
File "/Applications/MoonPlayer.app/Contents/Resources/plugins/upgrade_extras.py", line 41, in get_latest_commit
data = get_content(url)
File "/Applications/MoonPlayer.app/Contents/Resources/plugins/upgrade_extras.py", line 28, in get_content
return urlopen(url).read()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
context=self._context)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```
[在这里粘贴完整日志 / Please paste here]
```

**如果可能，请提供截图：/ If possible, please provide a screenshot too:**

> [您的截图 / Your screenshot]

**Comment by coslyk** [comment]
方法1：升级macOS到10.13以上
方法2：用Homebrew安装最新版python:
```
brew install python@2
```

**Comment by chingrun** [comment]
用方法2的方法仍然报一样的错误，会不会是anaconda造成的冲突呢？ @coslyk

**Comment by coslyk** [comment]
有可能，终端下执行 `which python` 的结果是什么？

**Comment by chingrun** [comment]
您好 执行which python 显示的是/Users/xxx/anaconda3/bin/python 是需要切换python版本吗？如何切换呢 谢谢您！ @coslyk

**Comment by coslyk** [comment]
检查下openssl是否正确配置好，可参见 https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version/51132779 下面的回答。

**Comment by coslyk** [comment]
[最新的Alpha版本](https://github.com/coslyk/moonplayer/releases)应当已经解决了该问题。
